language: node_js

os:
  - linux

node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"

env:
  global:
  - secure: jKTCY7zQ/8YsHjfTYOkzeEAH4WASb1Nt92dXvMgAzDB2/GmGlmRbp2wO/3/SABbHA7oow3Ocniayl3wp29WNkzffylnOC6g9ThFekTqBjdh/gpCDK/MBjJ+J/ZhIjhGjKGSddicyVyVhsEaO1ZlxSMUnLjUtAEkYAgjtxWD0QJnoke7JjKgqKSwKcK0nisJ2hbHMKEGj5J3IdeMPq4db66ofZnkNqPkGdG1irVmRVksTtC911eqq8EaSZuwbp8TaVrmF3JsVshoVbDTrIHrGjCM98YNi54W1gPhPHuKupENNAJcKAA6IRiWXG3frCAZJDkLpsj+RweGDLVgNpQfdrqi/K1NCfnENG4xfkAzW8vBl22TQmIysbVo6iMgtlGkYq4dgw6T3MTnVS5utqbqd0VMDRpoPZfjhZv0r+akwdS/6lgno6/T3bLAqlNThqCuhIdK7VMzgQ0PCkXEWEbF5XXZjjs8QwESqPImtP9ZXQ8oYaOts+QIxX7kHDxoLZWJ14vsuw1cIYM5gCIEUmEeSzbGH6SrU/USn+QU4HYgdNWsfkjraEli58ThrS1xb9/soF3at1hpAZWPaIH32bqL6XfQrPFwiF6VLu5C1g3tdEFox+ylArVOMAB6FUl9xonKyGRAkVYbRi9sGI/JpTOMYTbqiocb/qviKPTHv4l2/m5o=
install:
- npm install
before_script:
    - sudo apt-get update
    - sudo apt-get install apache2
    - sudo apt-get install php5
    - sudo ln -s $(pwd) /var/www/fis3
    - sudo service apache2 restart
script:
- '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash ./release-doc.sh || true'
#- sh ./release-doc.sh
- 'npm run-script test-travis'
after_script:
- 'npm install coveralls@2.10.0 && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js'
cache:
  directories:
  - node_modules
branches:
  only:
  - master
  - test-more-platform
sudo:
 - true
